import utils from "../lib/utils"

let s = 'eyJpc3MiOiJhdmF0YXJRckxvZ2luIiwib3BlbmlkIjoib1kydEc2dERHS3dReURoQk93Q0pRVVgwVXE3USIsInVuaW9uaWQiOiJvUXNZejUteW1ibEV6emxiTndJcjFjbEEwT3VzIiwibmJmIjoxNjg5OTIwODE4NTkwLCJleHAiOjE2OTAxODAwMTg1OTAsImp0aSI6IjkxNEZEMTgyOEYifQ'