name: Trigger auto deployment for pdf-proxy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/pdf-proxy-AutoDeployTrigger-4ff485f0-eb15-4aa8-8086-d50d1e631c1a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PDFPROXY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PDFPROXY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PDFPROXY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: chajian-docker.pkg.coding.net
          registryUsername: ${{ secrets.PDFPROXY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PDFPROXY_REGISTRY_PASSWORD }}
          containerAppName: pdf-proxy
          resourceGroup: free-forever
          imageToBuild: chajian-docker.pkg.coding.net/pdf-proxy:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


